### PR TITLE
introduced term composition for khatamirad

### PR DESCRIPTION
**Pull request by HendrikBorgelt**
Introduced the term composition into the vocabulary for khatamirad. Provenance is currently not correct as the term and namespace for khatamirad does not exist yet.

### CODE REVIEW

**Comment by dalito** [comment]
@HendrikBorgelt If this should be fully attributed to @khatamirad (fully = also in the git-history), he has to submit a PR under his account and we can close this one un-merged. Else we could merged it as co-authored by him.

**Comment by khatamirad** [comment]
> @HendrikBorgelt to fully attribute this to @khatamirad (fully = also in the git-history), he has to submit a PR from his account and we can close this one un-merged. Else we could merged this PR and mention him as co-author.

@HendrikBorgelt is a pull requet still required? I'm fine by mention as co-author

**Comment by dalito** [comment]
The current draft of the definition ``Concentration of main constituent elements of a material, expressed in weight percentage or mole fraction`` is too special for a very general term. Why only "main" constituents? Based on what criteria is a constituent element considered "main"? What is meant by element? Can composition be specified by concentration only?

Maybe you could try to define more precisely what you mean by "composition" and/or the context of use.

**Comment by HendrikBorgelt** [comment]
@khatamirad and @dalito, as i am currently involved in a comference and a lot of work projects I will just be a silent listeren and correct or dismiss the pull request based on your requests. @khatamirad if you want to test the pipeline fully, you can also make an apointment with me and we can finaliyse the submition after the discussion for the term is completed.

**Comment by khatamirad** [comment]
> @khatamirad and @dalito, as i am currently involved in a comference and a lot of work projects I will just be a silent listeren and correct or dismiss the pull request based on your requests. @khatamirad if you want to test the pipeline fully, you can also make an apointment with me and we can finaliyse the submition after the discussion for the term is completed.

since a master student is going to spend more time on this, I will wait for more input and then submit a PR all at once. I guess this is more straight forward

**Comment by HendrikBorgelt** [comment]
then I will close this pull request.

**Pull request closed without merging**
