### PR TITLE
Add new concepts heterogeneous catalysis

### PR DESCRIPTION
**Pull request by schumannj**
I added my first 10 concepts with definitions.

heterogeneous catalysis
thermal catalysis
heterogeneous catalyst
reaction feed
reagent
active site
stability measurement
kinetic measurement
reaction name
reaction type

### CODE REVIEW

**Comment by dalito** [comment]
The failure has nothing to do with your PR. It is caused by a too strict validation rule for GitHub usernames in the IDranges file. It turns out that GitHub usernames can include uppercase; they are case-insensitive in comparisons but case preserving. I'll change the regex in another PR.

**Comment by dalito** [comment]
I have released a fixed version of voc4cat-tool (0.7.9) and updated the workflows here. In order to get the updated workflow file, into your fork, you have to rebase your fork. Do you know how to do it? Here is some [info](https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/).

**Comment by schumannj** [comment]
Thanks @dalito, I have updated the branch. It didnt seem to have worked as a proper rebase. it this the reason why the workflow was not initiated?

**Comment by dalito** [comment]
The workflow has now run successfully. Your Excel file was converted to new turtle files that have been auto-commited. Then Excel was removed. You can look at the commit list to see this. The job was this one: https://github.com/nfdi4cat/voc4cat/actions/runs/7754383109/job/21147618851

So it was successful!

**Review by nmoust — APPROVED** [review]
Dear Julia, 

thank you for your contribution. I will approve the additions. I discussed briefly with @dalito and we might need to revisit some of the definitions at a later stage. For now it is important that we add definitions to as many concepts as possible.

Thanks again,

Nikos

**Pull request merged**
