### PR TITLE
Restructuring of concepts under "Physical Entities" top-level concept.

### PR DESCRIPTION
**Pull request by nmoust**
This PR focuses on the “Physical Entities” top-level concept. I collected concepts that fit under physical entities and restructured them under i) reactor, ii) equipment and iii) material. 

You can see a schematic of the new structure and the included concepts under:
https://coggle.it/diagram/Z1LGavQUY3gpFAOY/t/-/42d163500cf6168d1af70503f8c850d913bfe6ff9701f4c29c8291e135cbf71d

I tried to not go too deep, and some concepts are “flat” just below the i) ii) or iii) parent concepts. 
I also kept only “Is-A” relations, so I had to delete a few already existing parent-children relations. 
I added the following concepts:

| URI | Concept | Definition |
| ----------- | ----------- | ----------- |
| 0000187 | equipment | Apparatus, devices, and instruments employed in the construction and operation of experimental setups and the analysis of catalytic reactions and materials. |
| 0000188 | reactor equipment | Components being integral parts of a catalytic reactor. |
| 0000189 | optical equipment | Optical systems involved in light irradiation. |
| 0000190 | material | Substances used as catalysts, supports, or reactants in catalytic processes. |
| 0000191 | detector| A device designed to identify a measurable change or signal in a system, often providing a binary (detected / not detected) or a qualitative response. |
| 0000192 | sensor | A device that measures a specific physical or chemical property and converts it into readable signal, often for continuous monitoring. |
| 0000193 | electrochemical reactor | A reactor used to perform and study electrochemical reactions. |
| 0000194 | catalyst | A material that initiates or increases the rate of a catalytic reaction, without it being consumed in the process. |

First step toward solving #48

### CODE REVIEW

**Review by dalito — CHANGES_REQUESTED** [review]
Thanks for this start! It looks great. I only spotted two other part-of relations we should break:

image

- `electrochemical equipment` (..7250)
- `electrochemical setup` (..7230)

are collections (part-of). We should just move the siblings one level up (to same level as `beaker`) and keep both terms for now.
We could define two new collections to reflect this use case of grouping terms. 

@RoteKekse please make an issue if you need these collection for your use case.

**Comment by RoteKekse** [comment]
Hey @dalito my understanding would be that everything from `beaker`, to `electrode`, to `flow cell` is `electrochemical equipment and that an `electro chemical setup` is a collection of different equipment and an `electrolyte`

**Comment by dalito** [comment]
Yes, I think you understood this as I meant it. Once Nikos updates the PR it will be easier to see and check.

**Review by dalito — APPROVED** [review]
Looks fine now!

**Pull request merged**
